In [1]:
import pandas as pd
import numpy as np
from datetime import datetime

pd.options.display.max_rows = 150
pd.options.display.max_columns = 150

In [2]:
# 1. Create a DataFrame for the US-Accident data.
file_to_load = "../US_Accidents_Dec21_updated.csv"
accidents = pd.read_csv(file_to_load)
accidents.head()

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,Number,Street,Side,City,County,State,Zipcode,Country,Timezone,Airport_Code,Weather_Timestamp,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Direction,Wind_Speed(mph),Precipitation(in),Weather_Condition,Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,3,2016-02-08 00:37:08,2016-02-08 06:37:08,40.108910,-83.092860,40.112060,-83.031870,3.230,Between Sawmill Rd/Exit 20 and OH-315/Olentang...,NaN,Outerbelt E,R,Dublin,Franklin,OH,43017,US,US/Eastern,KOSU,2016-02-08 00:53:00,42.1,36.1,58.0,29.76,10.0,SW,10.4,0.00,Light Rain,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,2,2016-02-08 05:56:20,2016-02-08 11:56:20,39.865420,-84.062800,39.865010,-84.048730,0.747,At OH-4/OH-235/Exit 41 - Accident.,NaN,I-70 E,R,Dayton,Montgomery,OH,45424,US,US/Eastern,KFFO,2016-02-08 05:58:00,36.9,NaN,91.0,29.68,10.0,Calm,NaN,0.02,Light Rain,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Night,Night,Night
2,A-3,2,2016-02-08 06:15:39,2016-02-08 12:15:39,39.102660,-84.524680,39.102090,-84.523960,0.055,At I-71/US-50/Exit 1 - Accident.,NaN,I-75 S,R,Cincinnati,Hamilton,OH,45203,US,US/Eastern,KLUK,2016-02-08 05:53:00,36.0,NaN,97.0,29.70,10.0,Calm,NaN,0.02,Overcast,False,False,False,False,True,False,False,False,False,False,False,False,False,Night,Night,Night,Day
3,A-4,2,2016-02-08 06:51:45,2016-02-08 12:51:45,41.062130,-81.537840,41.062170,-81.535470,0.123,At Dart Ave/Exit 21 - Accident.,NaN,I-77 N,R,Akron,Summit,OH,44311,US,US/Eastern,KAKR,2016-02-08 06:54:00,39.0,NaN,55.0,29.65,10.0,Calm,NaN,NaN,Overcast,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Night,Day,Day
4,A-5,3,2016-02-08 07:53:43,2016-02-08 13:53:43,39.172393,-84.492792,39.170476,-84.501798,0.500,At Mitchell Ave/Exit 6 - Accident.,NaN,I-75 S,R,Cincinnati,Hamilton,OH,45217,US,US/Eastern,KLUK,2016-02-08 07:53:00,37.0,29.8,93.0,29.69,10.0,WSW,10.4,0.01,Light Rain,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day

In [3]:
# 2. Redefine columns in dataframe
accidents_updated = accidents[['Severity', 'Start_Time', 'State', 'Temperature(F)', 'Visibility(mi)', 'Wind_Speed(mph)', 'Precipitation(in)', 
    'Weather_Condition', 'Sunrise_Sunset']].copy()
accidents_updated.head()

,Severity,Start_Time,State,Temperature(F),Visibility(mi),Wind_Speed(mph),Precipitation(in),Weather_Condition,Sunrise_Sunset
0,3,2016-02-08 00:37:08,OH,42.1,10.0,10.4,0.00,Light Rain,Night
1,2,2016-02-08 05:56:20,OH,36.9,10.0,NaN,0.02,Light Rain,Night
2,2,2016-02-08 06:15:39,OH,36.0,10.0,NaN,0.02,Overcast,Night
3,2,2016-02-08 06:51:45,OH,39.0,10.0,NaN,NaN,Overcast,Night
4,3,2016-02-08 07:53:43,OH,37.0,10.0,10.4,0.01,Light Rain,Day

In [4]:
#3. Remove NaN values
accidents_updated = accidents_updated.dropna(axis=0, how="any")
accidents_updated.head()

,Severity,Start_Time,State,Temperature(F),Visibility(mi),Wind_Speed(mph),Precipitation(in),Weather_Condition,Sunrise_Sunset
0,3,2016-02-08 00:37:08,OH,42.1,10.0,10.4,0.00,Light Rain,Night
4,3,2016-02-08 07:53:43,OH,37.0,10.0,10.4,0.01,Light Rain,Day
7,2,2016-02-08 11:51:46,OH,33.1,0.5,3.5,0.08,Snow,Day
9,2,2016-02-08 15:16:43,OH,32.0,0.5,3.5,0.05,Snow,Day
10,2,2016-02-08 15:43:50,OH,33.8,3.0,4.6,0.03,Light Snow,Day

In [5]:
#4. Add 'year' index column from 'Start_Time' column
accidents_updated['year'] = pd.DatetimeIndex(accidents_updated['Start_Time']).year
accidents_updated.head()

,Severity,Start_Time,State,Temperature(F),Visibility(mi),Wind_Speed(mph),Precipitation(in),Weather_Condition,Sunrise_Sunset,year
0,3,2016-02-08 00:37:08,OH,42.1,10.0,10.4,0.00,Light Rain,Night,2016
4,3,2016-02-08 07:53:43,OH,37.0,10.0,10.4,0.01,Light Rain,Day,2016
7,2,2016-02-08 11:51:46,OH,33.1,0.5,3.5,0.08,Snow,Day,2016
9,2,2016-02-08 15:16:43,OH,32.0,0.5,3.5,0.05,Snow,Day,2016
10,2,2016-02-08 15:43:50,OH,33.8,3.0,4.6,0.03,Light Snow,Day,2016

In [6]:
#5. Add 'date' index column from 'Start_Time' column
accidents_updated['date'] = pd.DatetimeIndex(accidents_updated['Start_Time']).date
accidents_updated.head()

,Severity,Start_Time,State,Temperature(F),Visibility(mi),Wind_Speed(mph),Precipitation(in),Weather_Condition,Sunrise_Sunset,year,date
0,3,2016-02-08 00:37:08,OH,42.1,10.0,10.4,0.00,Light Rain,Night,2016,2016-02-08
4,3,2016-02-08 07:53:43,OH,37.0,10.0,10.4,0.01,Light Rain,Day,2016,2016-02-08
7,2,2016-02-08 11:51:46,OH,33.1,0.5,3.5,0.08,Snow,Day,2016,2016-02-08
9,2,2016-02-08 15:16:43,OH,32.0,0.5,3.5,0.05,Snow,Day,2016,2016-02-08
10,2,2016-02-08 15:43:50,OH,33.8,3.0,4.6,0.03,Light Snow,Day,2016,2016-02-08

In [7]:
#6. Review Dtypes for "date" column
accidents_updated.dtypes

Severity               int64
Start_Time            object
State                 object
Temperature(F)       float64
Visibility(mi)       float64
Wind_Speed(mph)      float64
Precipitation(in)    float64
Weather_Condition     object
Sunrise_Sunset        object
year                   int64
date                  object
dtype: object

In [8]:
#7. Change 'date' column to string
accidents_updated['date'] = pd.to_datetime(accidents_updated['date'])
accidents_updated.dtypes

Severity                      int64
Start_Time                   object
State                        object
Temperature(F)              float64
Visibility(mi)              float64
Wind_Speed(mph)             float64
Precipitation(in)           float64
Weather_Condition            object
Sunrise_Sunset               object
year                          int64
date                 datetime64[ns]
dtype: object

In [9]:
#K1. Create a Severity bin for "short_delay" and "long_delay"

Severity_replace_1 = [1, 2]
Severity_replace_2 = [3, 4]
Severity_replace_1

for x in Severity_replace_1:
    accidents_updated.Severity = accidents_updated.Severity.replace(x,"short_delay")

for y in Severity_replace_2:
    accidents_updated.Severity = accidents_updated.Severity.replace(y,"long_delay")
    
accidents_updated.Severity.value_counts()

short_delay    2108004
long_delay      137416
Name: Severity, dtype: int64

In [10]:
#K2. Create a Weather_Condition bin for "clear_weather" and "bad_weather"
clear_weather = ['Fair', 
                 'Clear', 
                 'Cloudy', 
                 'Mostly Cloudy', 
                 'Partly Cloudy', 
                 'Fair / Windy', 
                 'Cloudy / Windy', 
                 'Mostly Cloudy / Windy',
                 'Partly Cloudy / Windy',
                 'N/A Precipitation',
                 'Scattered Clouds',
                 'Overcast']
bad_weather = [
 'Light Rain',
 'Light Snow',
 'Fog',
 'Haze',
 'Rain',
 'Heavy Rain',
 'Thunder in the Vicinity',
 'T-Storm',
 'Light Drizzle',
 'Smoke',
 'Thunder',
 'Light Rain with Thunder',
 'Snow',
 'Wintry Mix',
 'Heavy T-Storm',
 'Light Rain / Windy',
 'Light Snow / Windy',
 'Drizzle',
 'Heavy Snow',
 'Rain / Windy',
 'Light Thunderstorms and Rain',
 'Shallow Fog',
 'Light Freezing Rain',
 'Patches of Fog',
 'Heavy Rain / Windy',
 'Haze / Windy',
 'Mist',
 'Showers in the Vicinity',
 'Heavy Thunderstorms and Rain',
 'Thunderstorms and Rain',
 'Snow / Windy',
 'Heavy T-Storm / Windy',
 'Light Freezing Drizzle',
 'Fog / Windy',
 'T-Storm / Windy',
 'Thunderstorm',
 'Thunder / Windy',
 'Heavy Snow / Windy',
 'Blowing Dust / Windy',
 'Blowing Dust',
 'Drizzle and Fog',
 'Heavy Drizzle',
 'Blowing Snow',
 'Snow and Sleet',
 'Light Drizzle / Windy',
 'Light Rain Shower',
 'Blowing Snow / Windy',
 'Wintry Mix / Windy',
 'Light Sleet',
 'Light Ice Pellets',
 'Sleet',
 'Smoke / Windy',
 'Freezing Rain',
 'Light Snow and Sleet',
 'Light Freezing Rain / Windy',
 'Small Hail',
 'Light Freezing Fog',
 'Ice Pellets',
 'Light Snow Shower',
 'Squalls / Windy',
 'Widespread Dust',
 'Rain Shower',
 'Snow and Sleet / Windy',
 'Widespread Dust / Windy',
 'Light Snow and Sleet / Windy',
 'Sand / Dust Whirlwinds',
 'Heavy Sleet',
 'Light Rain Showers',
 'Freezing Drizzle',
 'Light Snow with Thunder',
 'Tornado',
 'Drizzle / Windy',
 'Light Sleet / Windy',
 'Thunder / Wintry Mix',
 'Squalls',
 'Snow Grains',
 'Patches of Fog / Windy',
 'Partial Fog',
 'Hail',
 'Heavy Snow with Thunder',
 'Heavy Rain Shower',
 'Heavy Thunderstorms and Snow',
 'Rain Showers',
 'Freezing Rain / Windy',
 'Sand / Windy',
 'Thunder and Hail',
 'Light Blowing Snow',
 'Blowing Snow Nearby',
 'Snow and Thunder / Windy',
 'Thunder / Wintry Mix / Windy',
 'Drifting Snow',
 'Heavy Thunderstorms with Small Hail',
 'Sand / Dust Whirls Nearby',
 'Sleet / Windy',
 'Light Thunderstorms and Snow',
 'Blowing Sand',
 'Heavy Freezing Rain',
 'Heavy Freezing Drizzle',
 'Light Rain Shower / Windy',
 'Sand / Dust Whirlwinds / Windy',
 'Heavy Rain Shower / Windy',
 'Heavy Ice Pellets',
 'Thunder and Hail / Windy']

for x in clear_weather:
    accidents_updated.Weather_Condition = accidents_updated.Weather_Condition.replace(x,"clear_weather")

for y in bad_weather:
    accidents_updated.Weather_Condition = accidents_updated.Weather_Condition.replace(y,"bad_weather")
    
    
accidents_updated.Weather_Condition.value_counts()

clear_weather    1909465
bad_weather       335955
Name: Weather_Condition, dtype: int64

In [11]:
#8. Drop 'State_Time' column
accidents_updated = accidents_updated.drop('Start_Time', axis='columns')
accidents_updated.head()

,Severity,State,Temperature(F),Visibility(mi),Wind_Speed(mph),Precipitation(in),Weather_Condition,Sunrise_Sunset,year,date
0,long_delay,OH,42.1,10.0,10.4,0.00,bad_weather,Night,2016,2016-02-08
4,long_delay,OH,37.0,10.0,10.4,0.01,bad_weather,Day,2016,2016-02-08
7,short_delay,OH,33.1,0.5,3.5,0.08,bad_weather,Day,2016,2016-02-08
9,short_delay,OH,32.0,0.5,3.5,0.05,bad_weather,Day,2016,2016-02-08
10,short_delay,OH,33.8,3.0,4.6,0.03,bad_weather,Day,2016,2016-02-08

In [12]:
#9. Rename the columns for ease of use in SQL
accidents_updated.rename(columns = {'Severity':'severity', 
                                    'State':'state_code', 
                                    'Temperature(F)':'temperature_f', 
                                    'Visibility(mi)': 'visibility_mi',
                                    'Wind_Speed(mph)': 'wind_speed_mph',
                                    'Precipitation(in)': 'precipitation_in',
                                    'Weather_Condition': 'weather_condition',
                                    'Sunrise_Sunset': 'sunrise_sunset'}, inplace = True)
accidents_updated.head()

,severity,state_code,temperature_f,visibility_mi,wind_speed_mph,precipitation_in,weather_condition,sunrise_sunset,year,date
0,long_delay,OH,42.1,10.0,10.4,0.00,bad_weather,Night,2016,2016-02-08
4,long_delay,OH,37.0,10.0,10.4,0.01,bad_weather,Day,2016,2016-02-08
7,short_delay,OH,33.1,0.5,3.5,0.08,bad_weather,Day,2016,2016-02-08
9,short_delay,OH,32.0,0.5,3.5,0.05,bad_weather,Day,2016,2016-02-08
10,short_delay,OH,33.8,3.0,4.6,0.03,bad_weather,Day,2016,2016-02-08

In [13]:
#10. Create a PreCovid Dataframe
#accidents_updated = pd.PreCOVID_accidents(date)
start_date = '2018-06-01'
end_date = '2020-02-29'
# Select DataFrame rows between two dates
mask = (accidents_updated['date'] > start_date) & (accidents_updated['date'] <= end_date)
PreCOVID_accidents = accidents_updated.loc[mask]
PreCOVID_accidents.head()

,severity,state_code,temperature_f,visibility_mi,wind_speed_mph,precipitation_in,weather_condition,sunrise_sunset,year,date
582028,long_delay,NJ,89.0,10.0,5.0,0.0,clear_weather,Day,2019,2019-10-02
1295810,long_delay,LA,54.0,10.0,5.0,0.0,clear_weather,Day,2019,2019-11-01
1537770,long_delay,AZ,41.0,10.0,10.0,0.0,clear_weather,Night,2020,2020-02-16
1568027,long_delay,TX,79.0,10.0,25.0,0.0,bad_weather,Day,2019,2019-06-04
1756843,long_delay,VA,37.0,10.0,0.0,0.0,clear_weather,Night,2019,2019-10-19

In [14]:
#11. Create a new "classification" column in the PreCOVID dataframe
#(this will be important for the PreCOVID/COVID accidents_merged datafrome; see Step #24)
PreCOVID_accidents['classification'] = 'PreCOVID'
PreCOVID_accidents.head()

C:\Users\kirkj\anaconda3\envs\mlenv\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,severity,state_code,temperature_f,visibility_mi,wind_speed_mph,precipitation_in,weather_condition,sunrise_sunset,year,date,classification
582028,long_delay,NJ,89.0,10.0,5.0,0.0,clear_weather,Day,2019,2019-10-02,PreCOVID
1295810,long_delay,LA,54.0,10.0,5.0,0.0,clear_weather,Day,2019,2019-11-01,PreCOVID
1537770,long_delay,AZ,41.0,10.0,10.0,0.0,clear_weather,Night,2020,2020-02-16,PreCOVID
1568027,long_delay,TX,79.0,10.0,25.0,0.0,bad_weather,Day,2019,2019-06-04,PreCOVID
1756843,long_delay,VA,37.0,10.0,0.0,0.0,clear_weather,Night,2019,2019-10-19,PreCOVID

In [15]:
#12. Create a COVID Dataframe
#accidents_updated = pd.COVID_accidents(date)
start_date = '2020-03-01'
end_date = '2021-12-31'
# Select DataFrame rows between two dates
mask = (accidents_updated['date'] > start_date) & (accidents_updated['date'] <= end_date)
COVID_accidents = accidents_updated.loc[mask]
COVID_accidents.head()

,severity,state_code,temperature_f,visibility_mi,wind_speed_mph,precipitation_in,weather_condition,sunrise_sunset,year,date
224945,short_delay,MA,42.0,10.0,12.0,0.0,clear_weather,Night,2021,2021-03-10
224946,short_delay,CA,54.0,2.0,6.0,0.0,bad_weather,Night,2021,2021-07-30
224947,short_delay,MD,79.0,10.0,9.0,0.0,clear_weather,Day,2021,2021-10-15
224948,short_delay,WA,38.0,10.0,0.0,0.0,clear_weather,Day,2021,2021-12-21
224949,short_delay,CA,52.0,10.0,9.0,0.0,clear_weather,Day,2021,2021-12-09

In [16]:
#13. Create a new "classification" column in the COVID dataframe
#(this will be important for the PreCOVID/COVID accidents_merged datafrome; see Step #24)
COVID_accidents['classification'] = 'COVID'
COVID_accidents.head()

C:\Users\kirkj\anaconda3\envs\mlenv\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,severity,state_code,temperature_f,visibility_mi,wind_speed_mph,precipitation_in,weather_condition,sunrise_sunset,year,date,classification
224945,short_delay,MA,42.0,10.0,12.0,0.0,clear_weather,Night,2021,2021-03-10,COVID
224946,short_delay,CA,54.0,2.0,6.0,0.0,bad_weather,Night,2021,2021-07-30,COVID
224947,short_delay,MD,79.0,10.0,9.0,0.0,clear_weather,Day,2021,2021-10-15,COVID
224948,short_delay,WA,38.0,10.0,0.0,0.0,clear_weather,Day,2021,2021-12-21,COVID
224949,short_delay,CA,52.0,10.0,9.0,0.0,clear_weather,Day,2021,2021-12-09,COVID

In [17]:
# #14a. Get count of unique values in the 'Severity' column from 'accidents_upated' dataframe
# print(accidents_updated['severity'].value_counts())

In [18]:
# #14b. Get count of unique values for Severity column from 'PreCOVID_accidents'
# print(PreCOVID_accidents['severity'].value_counts())

In [19]:
# #14c. Get count of unique values for Severity Column from 'COVID_accidents'
# print(COVID_accidents['severity'].value_counts())

In [20]:
# #15a. Get count of unique values in the 'State' column from 'accidents_updated'
# print(accidents_updated['state_code'].value_counts())

In [21]:
# #15b. Get count of unique values in the 'State' column from 'PreCOVID_accidents'
# print(PreCOVID_accidents['state_code'].value_counts())

In [22]:
# #15c. Get count of unique values in the 'State' column from "COVID_accidents"
# print(COVID_accidents['state_code'].value_counts())

In [23]:
# #16a. Get count of unique values in the 'Weather_Condition' column from 'accidents_updated'
# print(accidents_updated['weather_condition'].value_counts())

In [24]:
# #16b. Get count of unique values in the 'Weather_Condition' column from 'PreCOVID_accidents'
# print(PreCOVID_accidents['weather_condition'].value_counts())

In [25]:
# #16c. Get count of unique values in the 'Weather_Condition' column from 'COVID_accidents'
# print(COVID_accidents['weather_condition'].value_counts())

In [26]:
# #17a. Get count of unique values in the 'Sunrise_Sunset' column from 'accidents_updated'
# print(accidents_updated['sunrise_sunset'].value_counts())

In [27]:
# #17b. Get count of unique values in the 'Sunrise_Sunset' column from 'PreCOVID_accidents'
# print(PreCOVID_accidents['sunrise_sunset'].value_counts())

In [28]:
# #17c. Get count of unique values in the 'Sunrise_Sunset' column from 'COVID_accidents'
# print(COVID_accidents['sunrise_sunset'].value_counts())

In [29]:
# #18a. Get count of unique values in the 'year' column from 'accidents_updated'
# print(accidents_updated['year'].value_counts())

In [30]:
# #18b. Get count of unique values in the 'year' column from 'PreCOVID_accidents'
# print(PreCOVID_accidents['year'].value_counts())

In [31]:
# #18c. Get count of unique values in the 'year' column from 'COVID_accidents'
# print(COVID_accidents['year'].value_counts())

In [32]:
# #19. Get count of unique values in the 'classification' column from "PreCOVID_accidents"
# print(PreCOVID_accidents['classification'].value_counts())

In [33]:
# #20. Get count of unique values in the 'classification' column from "COVID_accidents"
# print(COVID_accidents['classification'].value_counts())

In [34]:
# #21. Export Accidents_updated as a csv file
# accidents_updated.to_csv(r'..\accidents_updated.csv', index = False)

In [35]:
# #22. Export PreCOVID_accidents as a csv file
# PreCOVID_accidents.to_csv(r'..\PreCOVID_accidents.csv', index = False)

In [36]:
# #23. Eport COVID_accidents as a csv file
# COVID_accidents.to_csv(r'..\COVID_accidents.csv', index = False)

In [37]:
#24. Combine PreCOVID_accidents and COVID_accidents into one dataframe
accidents_merged = pd.concat([PreCOVID_accidents, COVID_accidents], ignore_index=True, sort=False)
accidents_merged.head()

,severity,state_code,temperature_f,visibility_mi,wind_speed_mph,precipitation_in,weather_condition,sunrise_sunset,year,date,classification
0,long_delay,NJ,89.0,10.0,5.0,0.0,clear_weather,Day,2019,2019-10-02,PreCOVID
1,long_delay,LA,54.0,10.0,5.0,0.0,clear_weather,Day,2019,2019-11-01,PreCOVID
2,long_delay,AZ,41.0,10.0,10.0,0.0,clear_weather,Night,2020,2020-02-16,PreCOVID
3,long_delay,TX,79.0,10.0,25.0,0.0,bad_weather,Day,2019,2019-06-04,PreCOVID
4,long_delay,VA,37.0,10.0,0.0,0.0,clear_weather,Night,2019,2019-10-19,PreCOVID

In [38]:
# #21. Eport COVID_accidents as a csv file
# accidents_merged.to_csv(r'..\accidents_merged.csv', index = False)

In [39]:
size = 250000
PreCOVID_sample = PreCOVID_accidents.sample(n=size, replace=False)
COVID_sample = COVID_accidents.sample(n=size, replace=False)

accidents_sample_merged = pd.concat([PreCOVID_sample, COVID_sample], ignore_index=True, sort=False)
accidents_sample_merged.head()

,severity,state_code,temperature_f,visibility_mi,wind_speed_mph,precipitation_in,weather_condition,sunrise_sunset,year,date,classification
0,short_delay,CA,76.0,10.0,9.0,0.0,clear_weather,Day,2019,2019-06-27,PreCOVID
1,short_delay,OR,67.0,10.0,0.0,0.0,clear_weather,Day,2019,2019-06-05,PreCOVID
2,long_delay,VA,52.0,10.0,8.0,0.0,clear_weather,Day,2019,2019-04-01,PreCOVID
3,short_delay,CA,66.0,10.0,6.0,0.0,clear_weather,Night,2019,2019-10-06,PreCOVID
4,short_delay,CA,59.0,10.0,0.0,0.0,clear_weather,Night,2020,2020-02-06,PreCOVID

In [40]:
print(accidents_sample_merged['classification'].value_counts())

PreCOVID    250000
COVID       250000
Name: classification, dtype: int64

In [41]:
#21. Eport COVID_accidents as a csv file
accidents_sample_merged.to_csv(r'..\accidents_sample_merged.csv', index = False)