In [1]:
import pandas as pd
import numpy as np
from datetime import datetime

In [2]:
# 1. Create a DataFrame for the US-Accident data.
file_to_load = "US_Accidents_Dec21_updated.csv"
accidents = pd.read_csv(file_to_load)
accidents.head()

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,3,2016-02-08 00:37:08,2016-02-08 06:37:08,40.108910,-83.092860,40.112060,-83.031870,3.230,Between Sawmill Rd/Exit 20 and OH-315/Olentang...,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,2,2016-02-08 05:56:20,2016-02-08 11:56:20,39.865420,-84.062800,39.865010,-84.048730,0.747,At OH-4/OH-235/Exit 41 - Accident.,...,False,False,False,False,False,False,Night,Night,Night,Night
2,A-3,2,2016-02-08 06:15:39,2016-02-08 12:15:39,39.102660,-84.524680,39.102090,-84.523960,0.055,At I-71/US-50/Exit 1 - Accident.,...,False,False,False,False,False,False,Night,Night,Night,Day
3,A-4,2,2016-02-08 06:51:45,2016-02-08 12:51:45,41.062130,-81.537840,41.062170,-81.535470,0.123,At Dart Ave/Exit 21 - Accident.,...,False,False,False,False,False,False,Night,Night,Day,Day
4,A-5,3,2016-02-08 07:53:43,2016-02-08 13:53:43,39.172393,-84.492792,39.170476,-84.501798,0.500,At Mitchell Ave/Exit 6 - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day

In [ ]:
# 2. Check the datatypes of your columns.
accidents.dtypes

In [ ]:
# 3. Redefine columns in dataframe
accidents_updated = accidents[['Severity', 'Start_Time', 'State', 'Temperature(F)', 'Visibility(mi)', 'Wind_Speed(mph)', 'Precipitation(in)', 
    'Weather_Condition', 'Sunrise_Sunset']].copy()
accidents_updated.head()

In [ ]:
#4. Add 'Year' index column from 'Start_Time' column
accidents_updated['year'] = pd.DatetimeIndex(accidents_updated['Start_Time']).year
accidents_updated.head()

In [ ]:
#5. Replace NaN values with Zeros 
#Wind_Speed(mph) zero means no wind speed was reported for that accident
#Precipitation(in) zero means no precipitation was reported for that accident
accidents_updated.fillna(0)

In [ ]:
#6. Get count of unique values in the 'Severity' column
print(accidents_updated['Severity'].value_counts())

In [ ]:
#7. Get count of unique values in the 'State' column
print(accidents_updated['State'].value_counts())

In [ ]:
#8. Get count of unique values in the 'Weather_Condition' column
print(accidents_updated['Weather_Condition'].value_counts())

In [ ]:
#9. Get count of unique values in the 'Sunrise_Sunset' column
print(accidents_updated['Sunrise_Sunset'].value_counts())

In [ ]:
#10. Get count of unique values in the 'year' column
print(accidents_updated['year'].value_counts())

In [ ]:
#11. Save clean dataframe 
accidents_updated.to_csv(r'C:\Users\new\Desktop\Final Project - Ssmith14\export_accidents_updated.csv', index=False)